sg-s/xolotl

c++/conductances/brookings/ACurrent.hpp, tests/test_conductances.m
=> Add ACurrent from Brookings et al. 2014

c++/conductances/goldman/Ap.hpp, c++/conductances/goldman/At.hpp, c++/conductances/goldman/Cal.hpp, c++/conductances/goldman/KCaP.hpp, c++/conductances/goldman/KCaT.hpp, c++/conductances/goldman/Proc.hpp, c++/conductances/kispersky/ACurrent.hpp, c++/conductances/kispersky/CaS.hpp, c++/conductances/kispersky/CaT.hpp, c++/conductances/kispersky/HCurrent.hpp, c++/conductances/kispersky/KCa.hpp, c++/conductances/kispersky/Kd.hpp, c++/conductances/kispersky/NaV.hpp, c++/conductances/nadim/int1/Kd.hpp, c++/conductances/nadim/int1/Na.hpp, c++/conductances/nadim/lg/Kd.hpp, c++/conductances/nadim/lg/NaV.hpp, c++/conductances/nadim/mcn1/Kd.hpp, c++/conductances/nadim/mcn1/NaV.hpp, c++/synapses/Electrical.hpp, c++/synapses/nadim/Axon.hpp, c++/synapses/nadim/Neurite.hpp, c++/synapses/nadim/Soma.hpp, tests/test_conductances.m
Add conductances from Kispersky _et al._ 2012, Nadim _et al._ 1998, and Goldman _et al._ 2001
=> Conductances

docs/source/compilers.rst
Clarifications to documentation which should mitigate trouble solving issues like #191.
=> Updates to fixing compiler problems on Linux

docs/source/faq.rst
=> Add FAQ to documentation

c++/conductances/heras/Novel.hpp, c++/conductances/heras/Shab.hpp, c++/conductances/heras/Shaker.hpp
Add conductances from [Heras *et al.* 2018](https://www.biorxiv.org/content/biorxiv/early/2018/06/13/344325.full.pdf).
=> Conductance heras

c++/conductances/soplata/reticular/CaT.hpp, c++/conductances/soplata/reticular/Kd.hpp, c++/conductances/soplata/reticular/NaV.hpp, c++/conductances/soplata/thalamocortical/CaT.hpp, c++/conductances/soplata/thalamocortical/HCurrent.hpp, c++/conductances/soplata/thalamocortical/Kd.hpp, c++/conductances/soplata/thalamocortical/NaV.hpp, c++/synapses/borgers/AMPAergic.hpp, c++/synapses/borgers/NMDAergic.hpp, c++/synapses/prinz/Cholinergic.hpp, c++/synapses/soplata/AMPAergic.hpp, c++/synapses/soplata/GABAergic.hpp
Conductances from here: https://github.com/asoplata/propofol-coupling-2017-mechanisms/
=> Conductances soplata

c++/synapses/cymbalyuk/Inhibitory.hpp
Add conductance from http://www.jneurosci.org.resources.library.brandeis.edu/content/22/24/10580/
=> Conductance cymbalyuk

README.md
=> Update figures, add paper citation

docs/how-to/construct-models.md, docs/how-to/create-multi-compartment-models.md
* Add new description of synapses using new formalism
* Add explanation of new formalism
* Add section on Axial synapse `gmax` computation
* Add section on size and shape of multi-compartment models
=> New synapse documentation and multi-compartment model details

docs/reference/xolotl-methods.md
=> Revert "Fixed typo"

docs/how-to/change-existing-models.md, docs/how-to/construct-models.md, docs/how-to/run-simulations.md, docs/tutorials/first-network.md
* Update network demo to use new synapse syntax
* Add more detail regarding find/get/set
* Describe mechanism and current outputs
=> Docs fixes

docs/how-to/create-multi-compartment-models.md
I hope this is just a typo in the documentation and not something wrong in the model?
=> Surface area formula incorrect

c++/synapses/borgers/AMPAergic.hpp, c++/synapses/borgers/NMDAergic.hpp
Fix two broken components that had stupid errors in them
=> Fixes to broken components

@xolotl/benchmark.m, @xolotl/plot.m, @xolotl/show.m, examples/demo_multi_compartment_clamp.m, interactive-demos/hodgkin-huxley/activation_func_plot_func.m, interactive-demos/hodgkin-huxley/refractory_period_callback.m
Use new package format for mtools
=> Replace prettyFig with figlib.pretty

docs/explanation/hashing.md, docs/faq.md, docs/troubleshooting.md, docs/tutorials/built-in-demos.md, docs/tutorials/first-neuron.md
* Add to troubleshooting page to clarify what to do in a few cases
* link to troubleshooting page in tutorials
* Make some things prettier (add LaTeX math, etc)
* Begin to write section on how xolotl is hashed
=> Documentation

docs/how-to/create-multi-compartment-models.md
=> minor fixes

c++/conductances/traub/Cal.hpp
Calcium conductance
https://www.physiology.org/doi/pdf/10.1152/jn.1991.66.2.635
=> Add conductance from Traub et al. 1991

docs/explanation/integration.md
Add to the integration page a description of the method and a short derivation.
=> Add Euler-Maruyama description

c++/conductances/soplata/MCurrent.hpp
=> Add MCurrent from Soplata et al. 2010

c++/mexTemplate.cpp, c++/network.hpp, docs/how-to/run-simulations.md, docs/how-to/voltage-clamp.md, docs/reference/c++/network.md, docs/tutorials/built-in-demos.md, docs/tutorials/first-network.md, examples/demo_clamp_rk4.m, make_cpp_docs.py
I _think_ it works. I've tested it with one of the demos (see `demo_clamp_rk4`) and a couple of toy models. Please try to break it.
=> Voltage clamp multi step

c++/synapses/borgers/NMDAergic.hpp
This is one of several potential fixes to the NMDA synapse. See #415 for details.
=> Spin off `u` into a separate variable

.gitmodules, make_docs.py, mkdocs.yml
* Add xgrid as a submodule
* Add xfit as a submodule
To Do:
* Update `make_docs.py` to make all documentation, including submodules
* Write tutorial for xfit
* Make sure that xgrid tutorial works
=> Submodules

c++/conductances/giovannini/CaN.hpp, c++/conductances/giovannini/CaT.hpp, c++/conductances/giovannini/Kd.hpp, c++/conductances/giovannini/MCurrent.hpp, c++/conductances/giovannini/NaV.hpp
Add conductances from https://hal.archives-ouvertes.fr/hal-01426362/file/Giovannini-ICAN-Hippocampus_submittedRev.pdf#cite.Jochems2015
The calcium mechanism is just the Buchholtz mechanism.
=> Giovannini model

@xfit/xfit.m, docs/how-to/fit-parameters.md
* Update xfit how-to document
* Draws from new demo
* Uses new xfit syntax
=> Xfit docs update

@xolotl/plotgbars.m
=> Docs plotgbars

c++/mechanism.hpp, c++/mechanisms/buchholtz/CalciumMech.hpp, c++/mechanisms/destexhe/CalciumMech.hpp, c++/mechanisms/goldwyn/CurrentNoise.hpp, c++/mechanisms/goldwyn/CurrentNoise2.hpp, c++/mechanisms/goldwyn/SubunitNoise.hpp, c++/mechanisms/liu/FSDController.hpp, c++/mechanisms/liu/FSDTarget.hpp, c++/mechanisms/oleary/CalciumSensor.hpp, c++/mechanisms/oleary/IntegralController.hpp, c++/mechanisms/prinz/CalciumMech.hpp, c++/mechanisms/soto-trevino/ProportionalController.hpp, c++/mechanisms/traub/CalciumMech.hpp
Add `getClass` string to each mechanism.
=> Mechanism get class

c++/conductances/soplata/CaT.hpp, c++/conductances/soplata/Kd.hpp, c++/conductances/soplata/NaV.hpp
`xolotl.testConductances` passed
=> Soplata conductances fix
